# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/fakedns/fakedns.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pp/dns/fakedns/fakedns.proto\x12\x1av2ray.core.app.dns.fakedns\x1a common/protoext/extensions.proto\"K\n\x0b\x46\x61keDnsPool\x12\x0f\n\x07ip_pool\x18\x01 \x01(\t\x12\x0f\n\x07lruSize\x18\x02 \x01(\x03:\x1a\x82\xb5\x18\t\n\x07service\x82\xb5\x18\t\x12\x07\x66\x61keDns\"k\n\x10\x46\x61keDnsPoolMulti\x12\x36\n\x05pools\x18\x01 \x03(\x0b\x32\'.v2ray.core.app.dns.fakedns.FakeDnsPool:\x1f\x82\xb5\x18\t\n\x07service\x82\xb5\x18\x0e\x12\x0c\x66\x61keDnsMultiBo\n\x1e\x63om.v2ray.core.app.dns.fakednsP\x01Z.github.com/v2fly/v2ray-core/v5/app/dns/fakedns\xaa\x02\x1aV2Ray.Core.App.Dns.Fakednsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.dns.fakedns.fakedns_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.v2ray.core.app.dns.fakednsP\001Z.github.com/v2fly/v2ray-core/v5/app/dns/fakedns\252\002\032V2Ray.Core.App.Dns.Fakedns'
  _FAKEDNSPOOL._options = None
  _FAKEDNSPOOL._serialized_options = b'\202\265\030\t\n\007service\202\265\030\t\022\007fakeDns'
  _FAKEDNSPOOLMULTI._options = None
  _FAKEDNSPOOLMULTI._serialized_options = b'\202\265\030\t\n\007service\202\265\030\016\022\014fakeDnsMulti'
  _FAKEDNSPOOL._serialized_start=95
  _FAKEDNSPOOL._serialized_end=170
  _FAKEDNSPOOLMULTI._serialized_start=172
  _FAKEDNSPOOLMULTI._serialized_end=279
# @@protoc_insertion_point(module_scope)
