# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/observatory/command/command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.observatory import config_pb2 as app_dot_observatory_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%app/observatory/command/command.proto\x12\"v2ray.core.app.observatory.command\x1a\x1c\x61pp/observatory/config.proto\"\'\n\x18GetOutboundStatusRequest\x12\x0b\n\x03Tag\x18\x01 \x01(\t\"Z\n\x19GetOutboundStatusResponse\x12=\n\x06status\x18\x01 \x01(\x0b\x32-.v2ray.core.app.observatory.ObservationResult\"\x08\n\x06\x43onfig2\xa9\x01\n\x12ObservatoryService\x12\x92\x01\n\x11GetOutboundStatus\x12<.v2ray.core.app.observatory.command.GetOutboundStatusRequest\x1a=.v2ray.core.app.observatory.command.GetOutboundStatusResponse\"\x00\x42\x87\x01\n&com.v2ray.core.app.observatory.commandP\x01Z6github.com/v2fly/v2ray-core/v5/app/observatory/command\xaa\x02\"V2Ray.Core.App.Observatory.Commandb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.observatory.command.command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n&com.v2ray.core.app.observatory.commandP\001Z6github.com/v2fly/v2ray-core/v5/app/observatory/command\252\002\"V2Ray.Core.App.Observatory.Command'
  _GETOUTBOUNDSTATUSREQUEST._serialized_start=107
  _GETOUTBOUNDSTATUSREQUEST._serialized_end=146
  _GETOUTBOUNDSTATUSRESPONSE._serialized_start=148
  _GETOUTBOUNDSTATUSRESPONSE._serialized_end=238
  _CONFIG._serialized_start=240
  _CONFIG._serialized_end=248
  _OBSERVATORYSERVICE._serialized_start=251
  _OBSERVATORYSERVICE._serialized_end=420
# @@protoc_insertion_point(module_scope)
