# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/commander/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pp/commander/config.proto\x12\x18v2ray.core.app.commander\x1a\x19google/protobuf/any.proto\x1a common/protoext/extensions.proto\"<\n\x06\x43onfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12%\n\x07service\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"5\n\x10ReflectionConfig:!\x82\xb5\x18\r\n\x0bgrpcservice\x82\xb5\x18\x0c\x12\nreflection\"K\n\x10SimplifiedConfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x03(\t:\x1c\x82\xb5\x18\t\n\x07service\x82\xb5\x18\x0b\x12\tcommanderBi\n\x1c\x63om.v2ray.core.app.commanderP\x01Z,github.com/v2fly/v2ray-core/v5/app/commander\xaa\x02\x18V2Ray.Core.App.Commanderb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.commander.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034com.v2ray.core.app.commanderP\001Z,github.com/v2fly/v2ray-core/v5/app/commander\252\002\030V2Ray.Core.App.Commander'
  _REFLECTIONCONFIG._options = None
  _REFLECTIONCONFIG._serialized_options = b'\202\265\030\r\n\013grpcservice\202\265\030\014\022\nreflection'
  _SIMPLIFIEDCONFIG._options = None
  _SIMPLIFIEDCONFIG._serialized_options = b'\202\265\030\t\n\007service\202\265\030\013\022\tcommander'
  _CONFIG._serialized_start=117
  _CONFIG._serialized_end=177
  _REFLECTIONCONFIG._serialized_start=179
  _REFLECTIONCONFIG._serialized_end=232
  _SIMPLIFIEDCONFIG._serialized_start=234
  _SIMPLIFIEDCONFIG._serialized_end=309
# @@protoc_insertion_point(module_scope)
