# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/log/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.log import log_pb2 as common_dot_log_dot_log__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pp/log/config.proto\x12\x12v2ray.core.app.log\x1a\x14\x63ommon/log/log.proto\x1a common/protoext/extensions.proto\"{\n\x10LogSpecification\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.v2ray.core.app.log.LogType\x12.\n\x05level\x18\x02 \x01(\x0e\x32\x1f.v2ray.core.common.log.Severity\x12\x0c\n\x04path\x18\x03 \x01(\t\"\xa9\x01\n\x06\x43onfig\x12\x33\n\x05\x65rror\x18\x06 \x01(\x0b\x32$.v2ray.core.app.log.LogSpecification\x12\x34\n\x06\x61\x63\x63\x65ss\x18\x07 \x01(\x0b\x32$.v2ray.core.app.log.LogSpecification:\x16\x82\xb5\x18\t\n\x07service\x82\xb5\x18\x05\x12\x03logJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06*5\n\x07LogType\x12\x08\n\x04None\x10\x00\x12\x0b\n\x07\x43onsole\x10\x01\x12\x08\n\x04\x46ile\x10\x02\x12\t\n\x05\x45vent\x10\x03\x42W\n\x16\x63om.v2ray.core.app.logP\x01Z&github.com/v2fly/v2ray-core/v5/app/log\xaa\x02\x12V2Ray.Core.App.Logb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.log.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.v2ray.core.app.logP\001Z&github.com/v2fly/v2ray-core/v5/app/log\252\002\022V2Ray.Core.App.Log'
  _CONFIG._options = None
  _CONFIG._serialized_options = b'\202\265\030\t\n\007service\202\265\030\005\022\003log'
  _LOGTYPE._serialized_start=397
  _LOGTYPE._serialized_end=450
  _LOGSPECIFICATION._serialized_start=100
  _LOGSPECIFICATION._serialized_end=223
  _CONFIG._serialized_start=226
  _CONFIG._serialized_end=395
# @@protoc_insertion_point(module_scope)
