# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tcp/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#transport/internet/tcp/config.proto\x12!v2ray.core.transport.internet.tcp\x1a\x19google/protobuf/any.proto\x1a common/protoext/extensions.proto\"v\n\x06\x43onfig\x12-\n\x0fheader_settings\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x1d\n\x15\x61\x63\x63\x65pt_proxy_protocol\x18\x03 \x01(\x08:\x18\x82\xb5\x18\x0b\n\ttransport\x82\xb5\x18\x05\x12\x03tcpJ\x04\x08\x01\x10\x02\x42\x84\x01\n%com.v2ray.core.transport.internet.tcpP\x01Z5github.com/v2fly/v2ray-core/v5/transport/internet/tcp\xaa\x02!V2Ray.Core.Transport.Internet.Tcpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.tcp.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.v2ray.core.transport.internet.tcpP\001Z5github.com/v2fly/v2ray-core/v5/transport/internet/tcp\252\002!V2Ray.Core.Transport.Internet.Tcp'
  _CONFIG._options = None
  _CONFIG._serialized_options = b'\202\265\030\013\n\ttransport\202\265\030\005\022\003tcp'
  _CONFIG._serialized_start=135
  _CONFIG._serialized_end=253
# @@protoc_insertion_point(module_scope)
