# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vless/outbound/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protocol import server_spec_pb2 as common_dot_protocol_dot_server__spec__pb2
from common.net import address_pb2 as common_dot_net_dot_address__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proxy/vless/outbound/config.proto\x12\x1fv2ray.core.proxy.vless.outbound\x1a!common/protocol/server_spec.proto\x1a\x18\x63ommon/net/address.proto\x1a common/protoext/extensions.proto\"C\n\x06\x43onfig\x12\x39\n\x05vnext\x18\x01 \x03(\x0b\x32*.v2ray.core.common.protocol.ServerEndpoint\"}\n\x10SimplifiedConfig\x12\x32\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32!.v2ray.core.common.net.IPOrDomain\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0c\n\x04uuid\x18\x03 \x01(\t:\x19\x82\xb5\x18\n\n\x08outbound\x82\xb5\x18\x07\x12\x05vlessB~\n#com.v2ray.core.proxy.vless.outboundP\x01Z3github.com/v2fly/v2ray-core/v5/proxy/vless/outbound\xaa\x02\x1fV2Ray.Core.Proxy.Vless.Outboundb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.vless.outbound.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#com.v2ray.core.proxy.vless.outboundP\001Z3github.com/v2fly/v2ray-core/v5/proxy/vless/outbound\252\002\037V2Ray.Core.Proxy.Vless.Outbound'
  _SIMPLIFIEDCONFIG._options = None
  _SIMPLIFIEDCONFIG._serialized_options = b'\202\265\030\n\n\010outbound\202\265\030\007\022\005vless'
  _CONFIG._serialized_start=165
  _CONFIG._serialized_end=232
  _SIMPLIFIEDCONFIG._serialized_start=234
  _SIMPLIFIEDCONFIG._serialized_end=359
# @@protoc_insertion_point(module_scope)
