# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/udp/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#transport/internet/udp/config.proto\x12!v2ray.core.transport.internet.udp\"\x08\n\x06\x43onfigB\x84\x01\n%com.v2ray.core.transport.internet.udpP\x01Z5github.com/v2fly/v2ray-core/v5/transport/internet/udp\xaa\x02!V2Ray.Core.Transport.Internet.Udpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.udp.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.v2ray.core.transport.internet.udpP\001Z5github.com/v2fly/v2ray-core/v5/transport/internet/udp\252\002!V2Ray.Core.Transport.Internet.Udp'
  _CONFIG._serialized_start=74
  _CONFIG._serialized_end=82
# @@protoc_insertion_point(module_scope)
