# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/loopback/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproxy/loopback/config.proto\x12\x19v2ray.core.proxy.loopback\x1a common/protoext/extensions.proto\";\n\x06\x43onfig\x12\x13\n\x0binbound_tag\x18\x01 \x01(\t:\x1c\x82\xb5\x18\n\n\x08outbound\x82\xb5\x18\n\x12\x08loopbackBl\n\x1d\x63om.v2ray.core.proxy.loopbackP\x01Z-github.com/v2fly/v2ray-core/v5/proxy/loopback\xaa\x02\x19V2Ray.Core.Proxy.Loopbackb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.loopback.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.v2ray.core.proxy.loopbackP\001Z-github.com/v2fly/v2ray-core/v5/proxy/loopback\252\002\031V2Ray.Core.Proxy.Loopback'
  _CONFIG._options = None
  _CONFIG._serialized_options = b'\202\265\030\n\n\010outbound\202\265\030\n\022\010loopback'
  _CONFIG._serialized_start=92
  _CONFIG._serialized_end=151
# @@protoc_insertion_point(module_scope)
