# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/instman/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pp/instman/config.proto\x12\x16v2ray.core.app.instman\x1a common/protoext/extensions.proto\"$\n\x06\x43onfig:\x1a\x82\xb5\x18\t\n\x07service\x82\xb5\x18\t\x12\x07instmanBc\n\x1a\x63om.v2ray.core.app.instmanP\x01Z*github.com/v2fly/v2ray-core/v5/app/instman\xaa\x02\x16V2Ray.Core.App.Instmanb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.instman.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.v2ray.core.app.instmanP\001Z*github.com/v2fly/v2ray-core/v5/app/instman\252\002\026V2Ray.Core.App.Instman'
  _CONFIG._options = None
  _CONFIG._serialized_options = b'\202\265\030\t\n\007service\202\265\030\t\022\007instman'
  _CONFIG._serialized_start=86
  _CONFIG._serialized_end=122
# @@protoc_insertion_point(module_scope)
