# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/kcp/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#transport/internet/kcp/config.proto\x12!v2ray.core.transport.internet.kcp\x1a\x19google/protobuf/any.proto\x1a common/protoext/extensions.proto\"\x14\n\x03MTU\x12\r\n\x05value\x18\x01 \x01(\r\"\x14\n\x03TTI\x12\r\n\x05value\x18\x01 \x01(\r\"\x1f\n\x0eUplinkCapacity\x12\r\n\x05value\x18\x01 \x01(\r\"!\n\x10\x44ownlinkCapacity\x12\r\n\x05value\x18\x01 \x01(\r\"\x1b\n\x0bWriteBuffer\x12\x0c\n\x04size\x18\x01 \x01(\r\"\x1a\n\nReadBuffer\x12\x0c\n\x04size\x18\x01 \x01(\r\"!\n\x0f\x43onnectionReuse\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\"\x1e\n\x0e\x45ncryptionSeed\x12\x0c\n\x04seed\x18\x01 \x01(\t\"\xc6\x04\n\x06\x43onfig\x12\x33\n\x03mtu\x18\x01 \x01(\x0b\x32&.v2ray.core.transport.internet.kcp.MTU\x12\x33\n\x03tti\x18\x02 \x01(\x0b\x32&.v2ray.core.transport.internet.kcp.TTI\x12J\n\x0fuplink_capacity\x18\x03 \x01(\x0b\x32\x31.v2ray.core.transport.internet.kcp.UplinkCapacity\x12N\n\x11\x64ownlink_capacity\x18\x04 \x01(\x0b\x32\x33.v2ray.core.transport.internet.kcp.DownlinkCapacity\x12\x12\n\ncongestion\x18\x05 \x01(\x08\x12\x44\n\x0cwrite_buffer\x18\x06 \x01(\x0b\x32..v2ray.core.transport.internet.kcp.WriteBuffer\x12\x42\n\x0bread_buffer\x18\x07 \x01(\x0b\x32-.v2ray.core.transport.internet.kcp.ReadBuffer\x12+\n\rheader_config\x18\x08 \x01(\x0b\x32\x14.google.protobuf.Any\x12?\n\x04seed\x18\n \x01(\x0b\x32\x31.v2ray.core.transport.internet.kcp.EncryptionSeed:$\x82\xb5\x18\x0b\n\ttransport\x82\xb5\x18\x05\x12\x03kcp\x82\xb5\x18\x08\x8a\xff)\x04mkcpJ\x04\x08\t\x10\nB\x84\x01\n%com.v2ray.core.transport.internet.kcpP\x01Z5github.com/v2fly/v2ray-core/v5/transport/internet/kcp\xaa\x02!V2Ray.Core.Transport.Internet.Kcpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.kcp.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.v2ray.core.transport.internet.kcpP\001Z5github.com/v2fly/v2ray-core/v5/transport/internet/kcp\252\002!V2Ray.Core.Transport.Internet.Kcp'
  _CONFIG._options = None
  _CONFIG._serialized_options = b'\202\265\030\013\n\ttransport\202\265\030\005\022\003kcp\202\265\030\010\212\377)\004mkcp'
  _MTU._serialized_start=135
  _MTU._serialized_end=155
  _TTI._serialized_start=157
  _TTI._serialized_end=177
  _UPLINKCAPACITY._serialized_start=179
  _UPLINKCAPACITY._serialized_end=210
  _DOWNLINKCAPACITY._serialized_start=212
  _DOWNLINKCAPACITY._serialized_end=245
  _WRITEBUFFER._serialized_start=247
  _WRITEBUFFER._serialized_end=274
  _READBUFFER._serialized_start=276
  _READBUFFER._serialized_end=302
  _CONNECTIONREUSE._serialized_start=304
  _CONNECTIONREUSE._serialized_end=337
  _ENCRYPTIONSEED._serialized_start=339
  _ENCRYPTIONSEED._serialized_end=369
  _CONFIG._serialized_start=372
  _CONFIG._serialized_end=954
# @@protoc_insertion_point(module_scope)
