# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protoext/testing/test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"common/protoext/testing/test.proto\x12\"v2ray.core.common.protoext.testing\x1a common/protoext/extensions.proto\"R\n\x0eTestingMessage\x12)\n\ntest_field\x18\x01 \x01(\tB\x15\x82\xb5\x18\x06\x12\x04test\x82\xb5\x18\x07\x12\x05test2:\x15\x82\xb5\x18\x06\n\x04\x64\x65mo\x82\xb5\x18\x07\n\x05\x64\x65mo2B\x84\x01\n&com.v2ray.core.common.protoext.testingP\x01Z3github.com/v2fly/v2ray-core/common/protoext/testing\xaa\x02\"V2Ray.Core.Common.ProtoExt.Testingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.protoext.testing.test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n&com.v2ray.core.common.protoext.testingP\001Z3github.com/v2fly/v2ray-core/common/protoext/testing\252\002\"V2Ray.Core.Common.ProtoExt.Testing'
  _TESTINGMESSAGE.fields_by_name['test_field']._options = None
  _TESTINGMESSAGE.fields_by_name['test_field']._serialized_options = b'\202\265\030\006\022\004test\202\265\030\007\022\005test2'
  _TESTINGMESSAGE._options = None
  _TESTINGMESSAGE._serialized_options = b'\202\265\030\006\n\004demo\202\265\030\007\n\005demo2'
  _TESTINGMESSAGE._serialized_start=108
  _TESTINGMESSAGE._serialized_end=190
# @@protoc_insertion_point(module_scope)
