# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/dns/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.net import destination_pb2 as common_dot_net_dot_destination__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proxy/dns/config.proto\x12\x14v2ray.core.proxy.dns\x1a\x1c\x63ommon/net/destination.proto\x1a common/protoext/extensions.proto\"M\n\x06\x43onfig\x12/\n\x06server\x18\x01 \x01(\x0b\x32\x1f.v2ray.core.common.net.Endpoint\x12\x12\n\nuser_level\x18\x02 \x01(\r\"+\n\x10SimplifiedConfig:\x17\x82\xb5\x18\n\n\x08outbound\x82\xb5\x18\x05\x12\x03\x64nsB]\n\x18\x63om.v2ray.core.proxy.dnsP\x01Z(github.com/v2fly/v2ray-core/v5/proxy/dns\xaa\x02\x14V2Ray.Core.Proxy.Dnsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.dns.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.v2ray.core.proxy.dnsP\001Z(github.com/v2fly/v2ray-core/v5/proxy/dns\252\002\024V2Ray.Core.Proxy.Dns'
  _SIMPLIFIEDCONFIG._options = None
  _SIMPLIFIEDCONFIG._serialized_options = b'\202\265\030\n\n\010outbound\202\265\030\005\022\003dns'
  _CONFIG._serialized_start=112
  _CONFIG._serialized_end=189
  _SIMPLIFIEDCONFIG._serialized_start=191
  _SIMPLIFIEDCONFIG._serialized_end=234
# @@protoc_insertion_point(module_scope)
