# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/shadowsocks/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.net import network_pb2 as common_dot_net_dot_network__pb2
from common.protocol import user_pb2 as common_dot_protocol_dot_user__pb2
from common.protocol import server_spec_pb2 as common_dot_protocol_dot_server__spec__pb2
from common.net.packetaddr import config_pb2 as common_dot_net_dot_packetaddr_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproxy/shadowsocks/config.proto\x12\x1cv2ray.core.proxy.shadowsocks\x1a\x18\x63ommon/net/network.proto\x1a\x1a\x63ommon/protocol/user.proto\x1a!common/protocol/server_spec.proto\x1a\"common/net/packetaddr/config.proto\"\x9a\x01\n\x07\x41\x63\x63ount\x12\x10\n\x08password\x18\x01 \x01(\t\x12=\n\x0b\x63ipher_type\x18\x02 \x01(\x0e\x32(.v2ray.core.proxy.shadowsocks.CipherType\x12\x10\n\x08iv_check\x18\x03 \x01(\x08\x12,\n\"experiment_reduced_iv_head_entropy\x18\x91\xbf\x05 \x01(\x08\"\xcc\x01\n\x0cServerConfig\x12\x17\n\x0budp_enabled\x18\x01 \x01(\x08\x42\x02\x18\x01\x12.\n\x04user\x18\x02 \x01(\x0b\x32 .v2ray.core.common.protocol.User\x12/\n\x07network\x18\x03 \x03(\x0e\x32\x1e.v2ray.core.common.net.Network\x12\x42\n\x0fpacket_encoding\x18\x04 \x01(\x0e\x32).v2ray.core.net.packetaddr.PacketAddrType\"J\n\x0c\x43lientConfig\x12:\n\x06server\x18\x01 \x03(\x0b\x32*.v2ray.core.common.protocol.ServerEndpoint*\\\n\nCipherType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0b\x41\x45S_128_GCM\x10\x01\x12\x0f\n\x0b\x41\x45S_256_GCM\x10\x02\x12\x15\n\x11\x43HACHA20_POLY1305\x10\x03\x12\x08\n\x04NONE\x10\x04\x42u\n com.v2ray.core.proxy.shadowsocksP\x01Z0github.com/v2fly/v2ray-core/v5/proxy/shadowsocks\xaa\x02\x1cV2Ray.Core.Proxy.Shadowsocksb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.shadowsocks.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.v2ray.core.proxy.shadowsocksP\001Z0github.com/v2fly/v2ray-core/v5/proxy/shadowsocks\252\002\034V2Ray.Core.Proxy.Shadowsocks'
  _SERVERCONFIG.fields_by_name['udp_enabled']._options = None
  _SERVERCONFIG.fields_by_name['udp_enabled']._serialized_options = b'\030\001'
  _CIPHERTYPE._serialized_start=629
  _CIPHERTYPE._serialized_end=721
  _ACCOUNT._serialized_start=190
  _ACCOUNT._serialized_end=344
  _SERVERCONFIG._serialized_start=347
  _SERVERCONFIG._serialized_end=551
  _CLIENTCONFIG._serialized_start=553
  _CLIENTCONFIG._serialized_end=627
# @@protoc_insertion_point(module_scope)
