# Generated by Django 3.2.18 on 2023-03-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('listen', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('streamSettings', models.JSONField(blank=True, null=True)),
                ('sniffing', models.JSONField(blank=True, null=True)),
                ('max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('up', models.PositiveBigIntegerField(default=0)),
                ('down', models.PositiveBigIntegerField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_proxy.inbound_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('uuid', models.UUIDField()),
                ('max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('up', models.PositiveBigIntegerField(default=0)),
                ('down', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vless',
            fields=[
                ('inbound_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proxy.inbound')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('proxy.inbound',),
        ),
        migrations.CreateModel(
            name='Vmess',
            fields=[
                ('inbound_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proxy.inbound')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('proxy.inbound',),
        ),
    ]
