# Generated by Django 3.2.18 on 2023-03-21 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('proxy', '0002_auto_20230320_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('cert', models.TextField()),
                ('key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tls', models.BooleanField(default=False)),
                ('tls_alpn', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='sniffing',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='streamSettings',
        ),
        migrations.AddField(
            model_name='inbound',
            name='sniffing_dest_override',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='sniffing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vless',
            name='decryption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Grpc',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proxy.transport')),
                ('service_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('proxy.transport',),
        ),
        migrations.CreateModel(
            name='Http',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proxy.transport')),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('proxy.transport',),
        ),
        migrations.CreateModel(
            name='Tcp',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proxy.transport')),
                ('accept_proxy_protocol', models.BooleanField(default=False)),
                ('header_type', models.CharField(default='none', max_length=100)),
                ('header_request_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('proxy.transport',),
        ),
        migrations.CreateModel(
            name='WebSocket',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proxy.transport')),
                ('accept_proxy_protocol', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('proxy.transport',),
        ),
        migrations.AddField(
            model_name='transport',
            name='inbound',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proxy.inbound'),
        ),
        migrations.AddField(
            model_name='transport',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_proxy.transport_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transport',
            name='tls_certificates',
            field=models.ManyToManyField(to='proxy.Certificate'),
        ),
        migrations.CreateModel(
            name='Fallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('alpn', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('dest', models.CharField(max_length=100)),
                ('xver', models.IntegerField(blank=True, null=True)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallbacks', to='proxy.vless')),
            ],
        ),
    ]
