# Generated by Django 3.2.18 on 2023-03-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_auto_20230321_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='inbound',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='proxy.inbound'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='tls_certificates',
            field=models.ManyToManyField(blank=True, to='proxy.Certificate'),
        ),
    ]
