# Generated by Django 3.2.18 on 2023-03-23 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_auto_20230323_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
