# Generated by Django 3.2.18 on 2023-03-26 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InboundAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_addresses', to='proxy.inbound')),
            ],
        ),
    ]
