# Generated by Django 3.2.18 on 2023-03-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0007_auto_20230329_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('up', models.PositiveBigIntegerField(default=0)),
                ('down', models.PositiveBigIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
                ('reset_period', models.DurationField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inbound',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='proxy.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='proxy.Group'),
        ),
    ]
