# Generated by Django 3.2.18 on 2023-03-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0008_auto_20230329_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users', to='proxy.Group'),
        ),
    ]
