# Generated by Django 3.2.18 on 2023-03-31 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0010_auto_20230331_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('up', models.PositiveBigIntegerField(default=0)),
                ('down', models.PositiveBigIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
                ('reset_period', models.DurationField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='proxy.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='proxy.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
