# Generated by Django 3.2.18 on 2023-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0012_trojan'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inbound',
            name='sni',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
