# Generated by Django 3.2.18 on 2023-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0014_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='groups', through='proxy.Membership', to='proxy.User'),
        ),
    ]
