# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/trojan/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protocol import user_pb2 as common_dot_protocol_dot_user__pb2
from common.protocol import server_spec_pb2 as common_dot_protocol_dot_server__spec__pb2
from common.net.packetaddr import config_pb2 as common_dot_net_dot_packetaddr_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proxy/trojan/config.proto\x12\x17v2ray.core.proxy.trojan\x1a\x1a\x63ommon/protocol/user.proto\x1a!common/protocol/server_spec.proto\x1a\"common/net/packetaddr/config.proto\"\x1b\n\x07\x41\x63\x63ount\x12\x10\n\x08password\x18\x01 \x01(\t\"P\n\x08\x46\x61llback\x12\x0c\n\x04\x61lpn\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x65st\x18\x04 \x01(\t\x12\x0c\n\x04xver\x18\x05 \x01(\x04\"J\n\x0c\x43lientConfig\x12:\n\x06server\x18\x01 \x03(\x0b\x32*.v2ray.core.common.protocol.ServerEndpoint\"\xb9\x01\n\x0cServerConfig\x12/\n\x05users\x18\x01 \x03(\x0b\x32 .v2ray.core.common.protocol.User\x12\x34\n\tfallbacks\x18\x03 \x03(\x0b\x32!.v2ray.core.proxy.trojan.Fallback\x12\x42\n\x0fpacket_encoding\x18\x04 \x01(\x0e\x32).v2ray.core.net.packetaddr.PacketAddrTypeBf\n\x1b\x63om.v2ray.core.proxy.trojanP\x01Z+github.com/v2fly/v2ray-core/v5/proxy/trojan\xaa\x02\x17V2Ray.Core.Proxy.Trojanb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.trojan.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.v2ray.core.proxy.trojanP\001Z+github.com/v2fly/v2ray-core/v5/proxy/trojan\252\002\027V2Ray.Core.Proxy.Trojan'
  _ACCOUNT._serialized_start=153
  _ACCOUNT._serialized_end=180
  _FALLBACK._serialized_start=182
  _FALLBACK._serialized_end=262
  _CLIENTCONFIG._serialized_start=264
  _CLIENTCONFIG._serialized_end=338
  _SERVERCONFIG._serialized_start=341
  _SERVERCONFIG._serialized_end=526
# @@protoc_insertion_point(module_scope)
