# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protocol import headers_pb2 as common_dot_protocol_dot_headers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proxy/vmess/account.proto\x12\x16v2ray.core.proxy.vmess\x1a\x1d\x63ommon/protocol/headers.proto\"\x85\x01\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x61lter_id\x18\x02 \x01(\r\x12\x45\n\x11security_settings\x18\x03 \x01(\x0b\x32*.v2ray.core.common.protocol.SecurityConfig\x12\x15\n\rtests_enabled\x18\x04 \x01(\tBc\n\x1a\x63om.v2ray.core.proxy.vmessP\x01Z*github.com/v2fly/v2ray-core/v5/proxy/vmess\xaa\x02\x16V2Ray.Core.Proxy.Vmessb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.vmess.account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.v2ray.core.proxy.vmessP\001Z*github.com/v2fly/v2ray-core/v5/proxy/vmess\252\002\026V2Ray.Core.Proxy.Vmess'
  _ACCOUNT._serialized_start=85
  _ACCOUNT._serialized_end=218
# @@protoc_insertion_point(module_scope)
