# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/reverse/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pp/reverse/config.proto\x12\x16v2ray.core.app.reverse\x1a common/protoext/extensions.proto\"o\n\x07\x43ontrol\x12\x34\n\x05state\x18\x01 \x01(\x0e\x32%.v2ray.core.app.reverse.Control.State\x12\x0e\n\x06random\x18\x63 \x01(\x0c\"\x1e\n\x05State\x12\n\n\x06\x41\x43TIVE\x10\x00\x12\t\n\x05\x44RAIN\x10\x01\"+\n\x0c\x42ridgeConfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\"+\n\x0cPortalConfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\"\x9e\x01\n\x06\x43onfig\x12;\n\rbridge_config\x18\x01 \x03(\x0b\x32$.v2ray.core.app.reverse.BridgeConfig\x12;\n\rportal_config\x18\x02 \x03(\x0b\x32$.v2ray.core.app.reverse.PortalConfig:\x1a\x82\xb5\x18\t\n\x07service\x82\xb5\x18\t\x12\x07reverseBg\n\x1c\x63om.v2ray.core.proxy.reverseP\x01Z*github.com/v2fly/v2ray-core/v5/app/reverse\xaa\x02\x18V2Ray.Core.Proxy.Reverseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.reverse.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034com.v2ray.core.proxy.reverseP\001Z*github.com/v2fly/v2ray-core/v5/app/reverse\252\002\030V2Ray.Core.Proxy.Reverse'
  _CONFIG._options = None
  _CONFIG._serialized_options = b'\202\265\030\t\n\007service\202\265\030\t\022\007reverse'
  _CONTROL._serialized_start=86
  _CONTROL._serialized_end=197
  _CONTROL_STATE._serialized_start=167
  _CONTROL_STATE._serialized_end=197
  _BRIDGECONFIG._serialized_start=199
  _BRIDGECONFIG._serialized_end=242
  _PORTALCONFIG._serialized_start=244
  _PORTALCONFIG._serialized_end=287
  _CONFIG._serialized_start=290
  _CONFIG._serialized_end=448
# @@protoc_insertion_point(module_scope)
