# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/taggedfeatures/skeleton.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$common/taggedfeatures/skeleton.proto\x12 v2ray.core.common.taggedfeatures\x1a\x19google/protobuf/any.proto\"\x99\x01\n\x06\x43onfig\x12H\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x36.v2ray.core.common.taggedfeatures.Config.FeaturesEntry\x1a\x45\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x42\x81\x01\n$com.v2ray.core.common.taggedfeaturesP\x01Z4github.com/v2fly/v2ray-core/v5/common/taggedfeatures\xaa\x02 V2Ray.Core.Common.Taggedfeaturesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.taggedfeatures.skeleton_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.v2ray.core.common.taggedfeaturesP\001Z4github.com/v2fly/v2ray-core/v5/common/taggedfeatures\252\002 V2Ray.Core.Common.Taggedfeatures'
  _CONFIG_FEATURESENTRY._options = None
  _CONFIG_FEATURESENTRY._serialized_options = b'8\001'
  _CONFIG._serialized_start=102
  _CONFIG._serialized_end=255
  _CONFIG_FEATURESENTRY._serialized_start=186
  _CONFIG_FEATURESENTRY._serialized_end=255
# @@protoc_insertion_point(module_scope)
