# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/tls/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+transport/internet/headers/tls/config.proto\x12)v2ray.core.transport.internet.headers.tls\"\x0e\n\x0cPacketConfigB\x9c\x01\n-com.v2ray.core.transport.internet.headers.tlsP\x01Z=github.com/v2fly/v2ray-core/v5/transport/internet/headers/tls\xaa\x02)V2Ray.Core.Transport.Internet.Headers.Tlsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.headers.tls.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.v2ray.core.transport.internet.headers.tlsP\001Z=github.com/v2fly/v2ray-core/v5/transport/internet/headers/tls\252\002)V2Ray.Core.Transport.Internet.Headers.Tls'
  _PACKETCONFIG._serialized_start=90
  _PACKETCONFIG._serialized_end=104
# @@protoc_insertion_point(module_scope)
