# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vless/inbound/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protocol import user_pb2 as common_dot_protocol_dot_user__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proxy/vless/inbound/config.proto\x12\x1ev2ray.core.proxy.vless.inbound\x1a\x1a\x63ommon/protocol/user.proto\x1a common/protoext/extensions.proto\"P\n\x08\x46\x61llback\x12\x0c\n\x04\x61lpn\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x65st\x18\x04 \x01(\t\x12\x0c\n\x04xver\x18\x05 \x01(\x04\"\x8c\x01\n\x06\x43onfig\x12\x31\n\x07\x63lients\x18\x01 \x03(\x0b\x32 .v2ray.core.common.protocol.User\x12\x12\n\ndecryption\x18\x02 \x01(\t\x12;\n\tfallbacks\x18\x03 \x03(\x0b\x32(.v2ray.core.proxy.vless.inbound.Fallback\";\n\x10SimplifiedConfig\x12\r\n\x05users\x18\x01 \x03(\t:\x18\x82\xb5\x18\t\n\x07inbound\x82\xb5\x18\x07\x12\x05vlessB{\n\"com.v2ray.core.proxy.vless.inboundP\x01Z2github.com/v2fly/v2ray-core/v5/proxy/vless/inbound\xaa\x02\x1eV2Ray.Core.Proxy.Vless.Inboundb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.vless.inbound.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"com.v2ray.core.proxy.vless.inboundP\001Z2github.com/v2fly/v2ray-core/v5/proxy/vless/inbound\252\002\036V2Ray.Core.Proxy.Vless.Inbound'
  _SIMPLIFIEDCONFIG._options = None
  _SIMPLIFIEDCONFIG._serialized_options = b'\202\265\030\t\n\007inbound\202\265\030\007\022\005vless'
  _FALLBACK._serialized_start=130
  _FALLBACK._serialized_end=210
  _CONFIG._serialized_start=213
  _CONFIG._serialized_end=353
  _SIMPLIFIEDCONFIG._serialized_start=355
  _SIMPLIFIEDCONFIG._serialized_end=414
# @@protoc_insertion_point(module_scope)
