# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/browserforwarder/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!app/browserforwarder/config.proto\x12\x1fv2ray.core.app.browserforwarder\x1a common/protoext/extensions.proto\"N\n\x06\x43onfig\x12\x13\n\x0blisten_addr\x18\x01 \x01(\t\x12\x13\n\x0blisten_port\x18\x02 \x01(\x05:\x1a\x82\xb5\x18\t\n\x07service\x82\xb5\x18\t\x12\x07\x62rowserB~\n#com.v2ray.core.app.browserforwarderP\x01Z3github.com/v2fly/v2ray-core/v5/app/browserforwarder\xaa\x02\x1fV2Ray.Core.App.Browserforwarderb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.browserforwarder.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#com.v2ray.core.app.browserforwarderP\001Z3github.com/v2fly/v2ray-core/v5/app/browserforwarder\252\002\037V2Ray.Core.App.Browserforwarder'
  _CONFIG._options = None
  _CONFIG._serialized_options = b'\202\265\030\t\n\007service\202\265\030\t\022\007browser'
  _CONFIG._serialized_start=104
  _CONFIG._serialized_end=182
# @@protoc_insertion_point(module_scope)
