# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/socks/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.net import address_pb2 as common_dot_net_dot_address__pb2
from common.net.packetaddr import config_pb2 as common_dot_net_dot_packetaddr_dot_config__pb2
from common.protocol import server_spec_pb2 as common_dot_protocol_dot_server__spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proxy/socks/config.proto\x12\x16v2ray.core.proxy.socks\x1a\x18\x63ommon/net/address.proto\x1a\"common/net/packetaddr/config.proto\x1a!common/protocol/server_spec.proto\"-\n\x07\x41\x63\x63ount\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\xf0\x02\n\x0cServerConfig\x12\x33\n\tauth_type\x18\x01 \x01(\x0e\x32 .v2ray.core.proxy.socks.AuthType\x12\x44\n\x08\x61\x63\x63ounts\x18\x02 \x03(\x0b\x32\x32.v2ray.core.proxy.socks.ServerConfig.AccountsEntry\x12\x32\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32!.v2ray.core.common.net.IPOrDomain\x12\x13\n\x0budp_enabled\x18\x04 \x01(\x08\x12\x13\n\x07timeout\x18\x05 \x01(\rB\x02\x18\x01\x12\x12\n\nuser_level\x18\x06 \x01(\r\x12\x42\n\x0fpacket_encoding\x18\x07 \x01(\x0e\x32).v2ray.core.net.packetaddr.PacketAddrType\x1a/\n\rAccountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"|\n\x0c\x43lientConfig\x12:\n\x06server\x18\x01 \x03(\x0b\x32*.v2ray.core.common.protocol.ServerEndpoint\x12\x30\n\x07version\x18\x02 \x01(\x0e\x32\x1f.v2ray.core.proxy.socks.Version*%\n\x08\x41uthType\x12\x0b\n\x07NO_AUTH\x10\x00\x12\x0c\n\x08PASSWORD\x10\x01*.\n\x07Version\x12\n\n\x06SOCKS5\x10\x00\x12\n\n\x06SOCKS4\x10\x01\x12\x0b\n\x07SOCKS4A\x10\x02\x42\x63\n\x1a\x63om.v2ray.core.proxy.socksP\x01Z*github.com/v2fly/v2ray-core/v5/proxy/socks\xaa\x02\x16V2Ray.Core.Proxy.Socksb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.socks.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.v2ray.core.proxy.socksP\001Z*github.com/v2fly/v2ray-core/v5/proxy/socks\252\002\026V2Ray.Core.Proxy.Socks'
  _SERVERCONFIG_ACCOUNTSENTRY._options = None
  _SERVERCONFIG_ACCOUNTSENTRY._serialized_options = b'8\001'
  _SERVERCONFIG.fields_by_name['timeout']._options = None
  _SERVERCONFIG.fields_by_name['timeout']._serialized_options = b'\030\001'
  _AUTHTYPE._serialized_start=693
  _AUTHTYPE._serialized_end=730
  _VERSION._serialized_start=732
  _VERSION._serialized_end=778
  _ACCOUNT._serialized_start=149
  _ACCOUNT._serialized_end=194
  _SERVERCONFIG._serialized_start=197
  _SERVERCONFIG._serialized_end=565
  _SERVERCONFIG_ACCOUNTSENTRY._serialized_start=518
  _SERVERCONFIG_ACCOUNTSENTRY._serialized_end=565
  _CLIENTCONFIG._serialized_start=567
  _CLIENTCONFIG._serialized_end=691
# @@protoc_insertion_point(module_scope)
