# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/routercommon/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$app/router/routercommon/common.proto\x12\"v2ray.core.app.router.routercommon\x1a common/protoext/extensions.proto\"\xab\x02\n\x06\x44omain\x12=\n\x04type\x18\x01 \x01(\x0e\x32/.v2ray.core.app.router.routercommon.Domain.Type\x12\r\n\x05value\x18\x02 \x01(\t\x12G\n\tattribute\x18\x03 \x03(\x0b\x32\x34.v2ray.core.app.router.routercommon.Domain.Attribute\x1aR\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x42\r\n\x0btyped_value\"6\n\x04Type\x12\t\n\x05Plain\x10\x00\x12\t\n\x05Regex\x10\x01\x12\x0e\n\nRootDomain\x10\x02\x12\x08\n\x04\x46ull\x10\x03\"?\n\x04\x43IDR\x12\n\n\x02ip\x18\x01 \x01(\x0c\x12\x0e\n\x06prefix\x18\x02 \x01(\r\x12\x1b\n\x07ip_addr\x18\xa0\x93\x04 \x01(\tB\x08\x82\xb5\x18\x04:\x02ip\"\xbb\x01\n\x05GeoIP\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\x36\n\x04\x63idr\x18\x02 \x03(\x0b\x32(.v2ray.core.app.router.routercommon.CIDR\x12\x15\n\rinverse_match\x18\x03 \x01(\x08\x12\x15\n\rresource_hash\x18\x04 \x01(\x0c\x12\x0c\n\x04\x63ode\x18\x05 \x01(\t\x12(\n\tfile_path\x18\xa0\x93\x04 \x01(\tB\x13\x82\xb5\x18\x0f\x32\rresource_hash\"E\n\tGeoIPList\x12\x38\n\x05\x65ntry\x18\x01 \x03(\x0b\x32).v2ray.core.app.router.routercommon.GeoIP\"\xaa\x01\n\x07GeoSite\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12:\n\x06\x64omain\x18\x02 \x03(\x0b\x32*.v2ray.core.app.router.routercommon.Domain\x12\x15\n\rresource_hash\x18\x03 \x01(\x0c\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12(\n\tfile_path\x18\xa0\x93\x04 \x01(\tB\x13\x82\xb5\x18\x0f\x32\rresource_hash\"I\n\x0bGeoSiteList\x12:\n\x05\x65ntry\x18\x01 \x03(\x0b\x32+.v2ray.core.app.router.routercommon.GeoSiteB\x87\x01\n&com.v2ray.core.app.router.routercommonP\x01Z6github.com/v2fly/v2ray-core/v5/app/router/routercommon\xaa\x02\"V2Ray.Core.App.Router.Routercommonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.router.routercommon.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n&com.v2ray.core.app.router.routercommonP\001Z6github.com/v2fly/v2ray-core/v5/app/router/routercommon\252\002\"V2Ray.Core.App.Router.Routercommon'
  _CIDR.fields_by_name['ip_addr']._options = None
  _CIDR.fields_by_name['ip_addr']._serialized_options = b'\202\265\030\004:\002ip'
  _GEOIP.fields_by_name['file_path']._options = None
  _GEOIP.fields_by_name['file_path']._serialized_options = b'\202\265\030\0172\rresource_hash'
  _GEOSITE.fields_by_name['file_path']._options = None
  _GEOSITE.fields_by_name['file_path']._serialized_options = b'\202\265\030\0172\rresource_hash'
  _DOMAIN._serialized_start=111
  _DOMAIN._serialized_end=410
  _DOMAIN_ATTRIBUTE._serialized_start=272
  _DOMAIN_ATTRIBUTE._serialized_end=354
  _DOMAIN_TYPE._serialized_start=356
  _DOMAIN_TYPE._serialized_end=410
  _CIDR._serialized_start=412
  _CIDR._serialized_end=475
  _GEOIP._serialized_start=478
  _GEOIP._serialized_end=665
  _GEOIPLIST._serialized_start=667
  _GEOIPLIST._serialized_end=736
  _GEOSITE._serialized_start=739
  _GEOSITE._serialized_end=909
  _GEOSITELIST._serialized_start=911
  _GEOSITELIST._serialized_end=984
# @@protoc_insertion_point(module_scope)
