# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/restfulapi/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pp/restfulapi/config.proto\x12\x14v2ray.app.restfulapi\x1a common/protoext/extensions.proto\"e\n\x06\x43onfig\x12\x13\n\x0blisten_addr\x18\x01 \x01(\t\x12\x13\n\x0blisten_port\x18\x02 \x01(\x05\x12\x12\n\nauth_token\x18\x03 \x01(\t:\x1d\x82\xb5\x18\t\n\x07service\x82\xb5\x18\x0c\x12\nrestfulapiBa\n\x1a\x63om.v2ray.core.app.restapiP\x01Z-github.com/v2fly/v2ray-core/v5/app/restfulapi\xaa\x02\x11V2Ray.App.Restapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.restfulapi.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.v2ray.core.app.restapiP\001Z-github.com/v2fly/v2ray-core/v5/app/restfulapi\252\002\021V2Ray.App.Restapi'
  _CONFIG._options = None
  _CONFIG._serialized_options = b'\202\265\030\t\n\007service\202\265\030\014\022\nrestfulapi'
  _CONFIG._serialized_start=87
  _CONFIG._serialized_end=188
# @@protoc_insertion_point(module_scope)
