# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tls/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#transport/internet/tls/config.proto\x12!v2ray.core.transport.internet.tls\x1a common/protoext/extensions.proto\"\xa5\x02\n\x0b\x43\x65rtificate\x12\x13\n\x0b\x43\x65rtificate\x18\x01 \x01(\x0c\x12\x0b\n\x03Key\x18\x02 \x01(\x0c\x12\x43\n\x05usage\x18\x03 \x01(\x0e\x32\x34.v2ray.core.transport.internet.tls.Certificate.Usage\x12-\n\x10\x63\x65rtificate_file\x18\x81\xee\x05 \x01(\tB\x11\x82\xb5\x18\r\"\x0b\x43\x65rtificate\x12\x1d\n\x08key_file\x18\x82\xee\x05 \x01(\tB\t\x82\xb5\x18\x05\"\x03Key\"a\n\x05Usage\x12\x10\n\x0c\x45NCIPHERMENT\x10\x00\x12\x14\n\x10\x41UTHORITY_VERIFY\x10\x01\x12\x13\n\x0f\x41UTHORITY_ISSUE\x10\x02\x12\x1b\n\x17\x41UTHORITY_VERIFY_CLIENT\x10\x03\"\xc3\x02\n\x06\x43onfig\x12\x1e\n\x0e\x61llow_insecure\x18\x01 \x01(\x08\x42\x06\x82\xb5\x18\x02(\x01\x12\x43\n\x0b\x63\x65rtificate\x18\x02 \x03(\x0b\x32..v2ray.core.transport.internet.tls.Certificate\x12\x13\n\x0bserver_name\x18\x03 \x01(\t\x12\x15\n\rnext_protocol\x18\x04 \x03(\t\x12!\n\x19\x65nable_session_resumption\x18\x05 \x01(\x08\x12\x1b\n\x13\x64isable_system_root\x18\x06 \x01(\x08\x12,\n$pinned_peer_certificate_chain_sha256\x18\x07 \x03(\x0c\x12!\n\x19verify_client_certificate\x18\x08 \x01(\x08:\x17\x82\xb5\x18\n\n\x08security\x82\xb5\x18\x05\x12\x03tlsB\x84\x01\n%com.v2ray.core.transport.internet.tlsP\x01Z5github.com/v2fly/v2ray-core/v5/transport/internet/tls\xaa\x02!V2Ray.Core.Transport.Internet.Tlsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.tls.config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.v2ray.core.transport.internet.tlsP\001Z5github.com/v2fly/v2ray-core/v5/transport/internet/tls\252\002!V2Ray.Core.Transport.Internet.Tls'
  _CERTIFICATE.fields_by_name['certificate_file']._options = None
  _CERTIFICATE.fields_by_name['certificate_file']._serialized_options = b'\202\265\030\r\"\013Certificate'
  _CERTIFICATE.fields_by_name['key_file']._options = None
  _CERTIFICATE.fields_by_name['key_file']._serialized_options = b'\202\265\030\005\"\003Key'
  _CONFIG.fields_by_name['allow_insecure']._options = None
  _CONFIG.fields_by_name['allow_insecure']._serialized_options = b'\202\265\030\002(\001'
  _CONFIG._options = None
  _CONFIG._serialized_options = b'\202\265\030\n\n\010security\202\265\030\005\022\003tls'
  _CERTIFICATE._serialized_start=109
  _CERTIFICATE._serialized_end=402
  _CERTIFICATE_USAGE._serialized_start=305
  _CERTIFICATE_USAGE._serialized_end=402
  _CONFIG._serialized_start=405
  _CONFIG._serialized_end=728
# @@protoc_insertion_point(module_scope)
